[package]
name = "eridani"
version = "0.1.0"
edition = "2021"
default-run = "eri"

[dependencies]
bimap = { version = "0.6", default-features = false }
clap = { version = "4.1", features = ["derive"], optional = true }
strum = { version = "0.24", default-features = false, features = ["derive"] }

[features]
default = ["compiler", "runtime", "std", "target_std"]
compiler = []
runtime = []
web = ["runtime"]
target_web = []
std = []
target_std = []
tree_walk = ["compiler", "runtime", "std", "target_std"]
bin = ["dep:clap", "tree_walk"]   # REMOVE DEPENDENCY ON TREE_WALK ONCE BYTECODE VM IS FINISHED

[lib]
crate_type = ["cdylib", "rlib"]

[[bin]]
name = "eri"
required-features = ["bin"]
