[package]
name = "eridani"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Pure functional scripting, anywhere"
repository = "https://github.com/Spartan2909/eridani"
documentation = "https://docs.rs/eridani/latest"
categories = ["compilers", "no-std"]
keywords = ["functional", "scripting"]

[dependencies]
eridani-common.workspace = true
eridani-compiler = { workspace = true, optional = true }
eridani-runtime = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

[build-dependencies]
rustc_version = "0.4.1"

[features]
default = ["compiler", "runtime", "std", "target_std"]
compiler = ["dep:eridani-compiler"]
runtime = ["dep:eridani-runtime"]
web = ["runtime"]
target_web = ["compiler"]
std = []
target_std = ["compiler"]
ffi = []
serde = ["dep:serde"]

[lib]
crate-type = ["cdylib", "rlib"]

[workspace]
members = ["eri", "eridani-common", "eridani-compiler", "eridani-runtime"]
package.edition = "2024"
package.license = "MIT"
package.rust-version = "1.85.0"

[workspace.dependencies]
eridani-common = { version = "0.1.0", path = "./eridani-common" }
eridani-compiler = { version = "0.1.0", path = "./eridani-compiler" }
eridani-runtime = { version = "0.1.0", path = "./eridani-runtime" }
hashbrown = "0.16.1"
serde = { version = "1.0.209", default-features = false, features = [
    "derive",
    "alloc",
] }
strum = { version = "0.27.2", default-features = false, features = ["derive"] }

[workspace.lints.rust]
unsafe_code = "deny"
unsafe_op_in_unsafe_fn = "forbid"

[workspace.lints.clippy]
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

cast_possible_truncation = "allow"
cast_possible_wrap = "allow"
cast_sign_loss = "allow"
multiple_unsafe_ops_per_block = "deny"
option_if_let_else = "allow"
redundant_pub_crate = "allow"
undocumented_unsafe_blocks = "deny"
use_self = "allow"
