name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
        settings-1: ['-p eri', '']

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        rustup toolchain add ${{ matrix.toolchain }} --component clippy
        rustup override set ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose ${{ matrix.settings-1 }}
    - name: Run tests
      run: cargo test --verbose ${{ matrix.settings-1 }}
    - name: Run Clippy
      run: cargo clippy --verbose ${{ matrix.settings-1 }}
  miri:
    name: Test with Miri
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          rustup toolchain add nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: Run Miri
        run: 'cargo miri test -p eri --verbose'
